export interface APIError {
  error: APIErrorType | string;
}

export enum APIErrorType {
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SESSION_EXPIRED = "SESSION_EXPIRED",
}
