services:
  database:
    image: postgres:15-alpine
    container_name: albion-raid-manager-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./packages/database/prisma/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: albion-raid-manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - albion-network

volumes:
  database-data:
    driver: local

networks:
  albion-network:
    driver: bridge 