import { memoize } from "@albion-raid-manager/common/helpers/cache";
import { sleep } from "@albion-raid-manager/common/scheduler";
import { getMilliseconds } from "@albion-raid-manager/common/utils/time";
import config from "@albion-raid-manager/config";
import { APIGuild } from "discord-api-types/v10";
import { discordApiClient } from "./client";
import { transformChannel, transformGuild, transformUser } from "./helpers";
import { Server } from "./types";

const DISCORD_TOKEN = config.discord.token;

export async function getCurrentUser(Authorization: string) {
  return memoize(
    `discord.users.${Authorization}`,
    async () => {
      const res = await discordApiClient.get(`/users/@me`, {
        headers: {
          Authorization,
        },
      });
      return transformUser(res.data);
    },
    {
      timeout: getMilliseconds(1, "days"),
    },
  );
}

export async function getUser(userId: string) {
  return memoize(
    `discord.users.${userId}`,
    async () => {
      const res = await discordApiClient.get(`/users/${userId}`, {
        headers: {
          Authorization: `Bot ${DISCORD_TOKEN}`,
        },
      });
      return transformUser(res.data);
    },
    {
      timeout: getMilliseconds(1, "days"),
    },
  );
}

export async function getUserGuilds(token: string): Promise<Server[]> {
  return memoize(
    `discord.users.${token}.guilds`,
    async () => {
      const res = await discordApiClient.get(`/users/@me/guilds`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      return res.data.map(transformGuild);
    },
    {
      timeout: getMilliseconds(1, "minutes"),
    },
  );
}

export async function getBotGuilds() {
  return memoize(
    `discord.bot.guilds`,
    async () => {
      let foundAll = false;
      let after;
      const guilds: APIGuild[] = [];

      // Iterate over all pages of guilds because bot can join more than the default 200 servers limit
      while (!foundAll) {
        const res = await discordApiClient.get<APIGuild[]>("/users/@me/guilds", {
          headers: {
            Authorization: `Bot ${DISCORD_TOKEN}`,
          },
          params: { limit: 200, after },
        });
        guilds.push(...res.data);

        after = guilds[guilds.length - 1].id;
        if (res.data.length < 200) foundAll = true;
        else await sleep(2000);
      }

      return guilds.map(transformGuild);
    },
    {
      refresh: getMilliseconds(10, "minutes"),
    },
  );
}

export async function getGuild(guildId: string) {
  return memoize(
    `discord.guilds.${guildId}`,
    async () => {
      const res = await discordApiClient.get(`/guilds/${guildId}`, {
        headers: {
          Authorization: `Bot ${DISCORD_TOKEN}`,
        },
      });
      return transformGuild(res.data);
    },
    {
      timeout: getMilliseconds(1, "days"),
    },
  );
}

export async function getGuildChannels(guildId: string) {
  return memoize(
    `discord.guilds.${guildId}.channels`,
    async () => {
      const res = await discordApiClient.get(`/guilds/${guildId}/channels`, {
        headers: {
          Authorization: `Bot ${DISCORD_TOKEN}`,
        },
      });
      return res.data.map(transformChannel);
    },
    {
      timeout: getMilliseconds(30, "seconds"),
    },
  );
}

export async function leaveGuild(guildId: string) {
  const res = await discordApiClient.delete(`/users/@me/guilds/${guildId}`, {
    headers: {
      Authorization: `Bot ${DISCORD_TOKEN}`,
    },
  });
  return res.data;
}

export const addMemberRole = async (guildId: string, memberId: string, roleId: string, reason: string) => {
  const res = await discordApiClient.put(`/guilds/${guildId}/members/${memberId}/roles/${roleId}`, null, {
    headers: {
      Authorization: `Bot ${DISCORD_TOKEN}`,
      "X-Audit-Log-Reason": reason,
    },
  });
  return res.data;
};

export const removeMemberRole = async (guildId: string, memberId: string, roleId: string, reason: string) => {
  const res = await discordApiClient.delete(`/guilds/${guildId}/members/${memberId}/roles/${roleId}`, {
    headers: {
      Authorization: `Bot ${DISCORD_TOKEN}`,
      "X-Audit-Log-Reason": reason,
    },
  });
  return res.data;
};

type File = {
  id: number;
  name: string;
  description: string;
  image: string;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const sendMessage = async (channelId: string, payload: any) => {
  if (!payload) throw new Error("Empty message");

  // If we have files (generated by embeds helper), transform them to attachments
  const files: File[] = [];
  if (payload.files && payload.files.length > 0) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    payload.files.forEach((file: any, i: number) => {
      files.push({
        id: i,
        description: file.description,
        name: file.name,
        image: file.attachment,
      });
    });
    delete payload.files;
    payload.attachments = files.map((file) => ({
      id: file.id,
      description: file.description,
      name: file.name,
    }));
  }

  const form = new FormData();
  form.append("payload_json", JSON.stringify(payload));
  files.forEach((file) => {
    form.append(`files[${file.id}]`, new Blob([file.image]), file.name);
  });

  const res = await discordApiClient.postForm(`/channels/${channelId}/messages`, form, {
    headers: {
      Authorization: `Bot ${DISCORD_TOKEN}`,
    },
  });
  return res.data;
};
