name: Release API

on:
  push:
    branches: [main]
    paths:
      - "apps/api/**"
      - "packages/core/**"
      - "packages/types/**"
      - "package.json"
      - "pnpm-workspace.yaml"
      - "pnpm-lock.yaml"

jobs:
  deploy-api:
    name: Build and push API image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: |
            agnjunio/albion-raid-manager:api
          cache-from: type=gha
          cache-to: type=gha,mode=max
